AgriculturalRecommendation/urls.py
#-*- coding:utf-8 -*-
"""AgriculturalRecommendation URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from AgriculturalRecommendation.settings import MEDIA_ROOT
from django.views.static import serve
from recommend_templates.views import NewsViewSet, ForumViewSet, SmsCodeViewSet, \
    UserViewSet, UserFavViewSet, UserBrowserHistoryViewSet, UserForumViewSet, LeaveViewSet, \
    ClassifySet,HotViewSet
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token

router = DefaultRouter()
router.register(r'news', NewsViewSet, base_name='news')
router.register(r'forums', ForumViewSet, base_name='forum')
router.register(r'leave', LeaveViewSet , base_name='leave')
router.register(r'code', SmsCodeViewSet, base_name='code')
router.register(r'users', UserViewSet, base_name='user')
router.register(r'userfavs', UserFavViewSet, base_name='userfavs')
router.register(r'userforums', UserForumViewSet, base_name='userforum')
router.register(r'browserhistory', UserBrowserHistoryViewSet, base_name='browserhistory')
router.register(r'classfiy', ClassifySet, base_name='classfiy')
router.register(r'hot', HotViewSet, base_name='hot')


urlpatterns = [
    # 后台
    url(r'^admin/', include(admin.site.urls)),
    # drf
    url(r'^login/', obtain_jwt_token),
    url(r'^docs/', include_docs_urls(title='个人新闻')),
    url(r'^', include(router.urls)),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

recommend_templates/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser

class UserProfile(AbstractUser):
    """
    扩展用户类
    """
    nick_name = models.CharField(max_length=50, verbose_name=u'昵称', default=u'')
    gender = models.CharField(max_length=10, choices=(('male', u'男'), ('female', u'女')), default=u'')
    mobile = models.CharField(max_length=11, null=True, blank=True)
    image = models.ImageField(upload_to='image/%Y/%m', default='img/default.png')
    birday = models.DateField(verbose_name=u'生日', null=True, blank=True)
    real_name = models.CharField(max_length=20, verbose_name=u'真实姓名', null=True, blank=True, default='')
    education = models.CharField(max_length=20, verbose_name=u'教育经历', null=True, blank=True, default='')
    expertise = models.CharField(max_length=20, verbose_name=u'专业技能', null=True, blank=True, default='')
    field = models.CharField(max_length=20, verbose_name=u'熟悉领域', null=True, blank=True, default='')
    third_party = models.CharField(max_length=20, verbose_name=u'第三方登录', null=True, blank=True, default='')

    class Meta:
        verbose_name = u'用户信息'
        verbose_name_plural = verbose_name

        def __str__(self):
            return self.username

class VerifyCode(models.Model):
    """
    短信验证码
    """
    code = models.CharField(verbose_name=u'验证码', max_length=6)
    moblie = models.CharField(verbose_name=u'手机号', max_length=11)
    created_at = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True, null=True)
    class Meta:
        verbose_name = u'短信验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.code

class Classify(models.Model):
    """
    分类
    """
    name = models.CharField(verbose_name='中文名', max_length=20)
    desc = models.CharField(verbose_name='缩写', max_length=10)
    created_at = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True, null=True)
    class Meta:
        verbose_name = u'分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class News(models.Model):
    """
    新闻
    """
    title = models.CharField(verbose_name=u'标题', max_length=50, unique=True)
    url = models.URLField(verbose_name=u'文章url链接', default='')
    classify = models.ForeignKey(Classify, verbose_name=u'分类')
    label = models.CharField(verbose_name=u'标签', max_length=20)
    text = models.TextField(verbose_name=u'内容')
    page_view = models.IntegerField(verbose_name=u'浏览次数', default=0)
    created_at = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name=u'更新时间', auto_now=True)
    exist = models.BooleanField(verbose_name=u'状态', default=True)

    class Meta:
        verbose_name = u'新闻'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

class BrowserHistory(models.Model):
    """
    用户浏览记录
    """
    user = models.ForeignKey(UserProfile, verbose_name=u'用户id')
    news = models.ForeignKey(News, verbose_name=u'新闻id')
    created_at = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True)

    class Meta:
        verbose_name = u'用户浏览记录'
        verbose_name_plural = verbose_name


class Forum(models.Model):
    """
    用户问答
    """
    type_list = (
        ('jg', '价格'),
        ('fxyc', '分析预测'),
        ('syjs', '实用技术'),
    )
    status_list = (
        ('dhd', '待回答'),
        ('yjj', '已解决'),
    )
    user = models.ForeignKey(UserProfile, verbose_name=u'用户id')
    title = models.CharField(verbose_name=u'帖子标题', max_length=50)
    type = models.CharField(verbose_name=u'帖子分类', max_length=20, choices=type_list)
    content = models.TextField(verbose_name=u'内容')
    page_view = models.IntegerField(verbose_name=u'浏览次数', default=0)
    compliment_num = models.IntegerField(verbose_name=u'点赞数量', default=0)
    collect_num = models.IntegerField(verbose_name=u'收藏数量', default=0)
    status = models.CharField(verbose_name=u'帖子状态', max_length=20, choices=status_list)
    created_at = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name=u'更新时间', auto_now=True)
    exist = models.BooleanField(verbose_name=u'状态', default=True)

    class Meta:
        verbose_name = '帖子'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

class Leave(models.Model):
    """
    帖子留言
    """
    user = models.ForeignKey(UserProfile, verbose_name=u'用户')
    forum = models.ForeignKey(Forum, verbose_name=u'帖子')
    content = models.TextField(verbose_name=u'留言')
    created_at = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True)

    class Meta:
        verbose_name = '留言'
        verbose_name_plural = verbose_name


class UserFav(models.Model):
    """
    用户收藏
    """
    user = models.ForeignKey(UserProfile, verbose_name=u'用户')
    news = models.ForeignKey(News, verbose_name=u'新闻')
    created_at = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True)
    class Meta:
        verbose_name = '收藏'
        verbose_name_plural = verbose_name
        unique_together = ('user', 'news')
    def __str__(self):
        return self.user.username

recommend_templates/forms.py
# _*_ coding:utf-8 _*_

from django import forms

from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)


class RegisterForm(forms.Form):
    email = forms.CharField(required=True)
    password = forms.CharField(required=True)
    captcha = CaptchaField(error_messages={'invalid': u'验证码错误！'})


class ForumForm(forms.Form):
    title = forms.CharField(required=True)
    types = forms.CharField(required=True)
    content = forms.CharField(required=True)
    status = forms.CharField(required=True)

templates/askanswer.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load staticfiles %}
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- 新 Bootstrap 核心 CSS 文件 -->
	<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
	<!-- 可选的Bootstrap主题文件（一般不用引入） -->
	<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

	<title>问答社区</title>
    <style>
        .askans {
            list-style-type: none;
            line-height: 40px;
        }
        .askans a:hover {
            color: red;
            text-decoration: none;
        }
        .askans span {
            float: right;
            margin: 0 10px;
        }
        .searchform {
            {#border: solid 1px red;#}
            position: relative;
            padding-top: 20px;
            float: right;
            padding-right: 100px;
        }
        #search {
            border: #00a0f0 solid 1px;
        }
        .asktable {
            width: 400px;
            font-size: 22px;
        }
        .asktable2 {
            width: 200px;
            font-size: 22px;
        }
        .asktd {
            line-height: 40px;
            font-size: 22px;
        }
    </style>
</head>


<body >  <!--页面背景色-->
	<div class="text-center" >
        <img style="display: block;height: 100px;" src="{% static 'img/news.png' %}" alt="logo" id="image" class="text-center"/>
		<ul id = "result" class="nav nav-tabs">
			<li role="presentation" class="active" ><a href="{% url 'index' %}">首页</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'news' %}">农业新闻</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'shichangjiage' %}">市场价格</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'shiyongjishu' %}">实用技术</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'zhengcefagui' %}">政策法规</a></li>
			<li role="presentation"><a href="{% url 'forum' %}">问答社区</a></li>
			{% if request.user.is_authenticated %}
				<li role="presentation"><a href="{% url 'user' 'history' %}">历史浏览</a></li>
				<li role="presentation"><a href="/myRecommend">我的推荐</a></li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'logout' %}"> 登出 </a> </li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'user' "info" %}"> {{ request.user.username  }} </a> </li>

			{% else %}
				<li class = "pull-right " role="presentation"> <a href="{% url 'login' %}"> 登录 </a> </li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'register' %}"> 注册 </a> </li>
			{% endif %}
		</ul>
	</div>
<div>
    <div style="width: 80%;height:700px;margin: 0 auto;">
        <form action="#" class="searchform">
            <input type="text" id="search" value="">
            <input type="submit" id="submit" value="搜索">
        </form>
        <a style="text-decoration: none;" href="{% url 'addforum' %}"><img src="{% static 'img/jiahao.jpg' %}" width="50px" height="50px">添加新的问答</a>
        <h1 style="text-align: center;">问答社区</h1><br/>

        <table style="width: 80%;">
            <tr>
                <th class="asktable">问题</th>
                <th class="asktable2">类型</th>
                <th class="asktable2">提问人</th>
                <th class="asktable2">时间</th>
            </tr>
            {% for forum in forums %}
            <tr>
                <td class="asktd"><a href="">{{ forum.title }}</a></td>
                <td class="asktd">{{ forum.get_type_display }}</td>
                <td class="asktd">{{ forum.user_id }}</td>
                <td class="asktd">{{ forum.updated_at }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div style="height: 50px;width: 100%;float: left; text-align: center;line-height: 50px;">
        <span style="color: red;">底部占位······</span>
    </div>
</div>
</body>
</html>

templates/classfiy.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load staticfiles %}
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- 新 Bootstrap 核心 CSS 文件 -->
	<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
	<!-- 可选的Bootstrap主题文件（一般不用引入） -->
	<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

	<title>果农帮新闻推荐系统</title>
</head>


<body >  <!--页面背景色-->


	<div class="text-center" >
        <img style="display: block;height: 100px;" src="{% static 'img/news.png' %}" alt="logo" id="image" class="text-center"/>
		<ul id = "result" class="nav nav-tabs">
			<li role="presentation" class="active" ><a href="{% url 'index' %}">首页</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'news' %}">农业新闻</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'shichangjiage' %}">市场价格</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'shiyongjishu' %}">实用技术</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'zhengcefagui' %}">政策法规</a></li>
            <li role="presentation"><a href="{% url 'forum' %}">问答社区</a></li>
			{% if request.user.is_authenticated %}
				<li role="presentation"><a href="{% url 'user' 'history' %}">历史浏览</a></li>
				<li role="presentation"><a href="/myRecommend">我的推荐</a></li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'logout' %}"> 登出 </a> </li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'user' "info" %}"> {{ request.user.username  }} </a> </li>
			{% else %}
				<li class = "pull-right " role="presentation"> <a href="{% url 'login' %}"> 登录 </a> </li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'register' %}"> 注册 </a> </li>
			{% endif %}
		</ul>
	</div>
<div>
    <div style="width: 100%;margin: 20px auto;padding:20px 300px;float: left">
        <h3 style="text-align: center;">{{ title }}</h3>
        <ul >
            {% for  news in news_all %}
            <li><span style="float: right;padding-right: 5px;">时间：{{ news.updated_at | date:"Y-m-d"}}</span><a href="{% url 'detail' news.id %}">{{ news.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
</body>
</html>

templates/details.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load staticfiles %}
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- 新 Bootstrap 核心 CSS 文件 -->
	<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
	<!-- 可选的Bootstrap主题文件（一般不用引入） -->
	<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

	<title>果农帮新闻推荐系统</title>
</head>


<body >  <!--页面背景色-->


	<div class="text-center" >
        <img style="display: block;height: 100px;" src="{% static 'img/news.png' %}" alt="logo" id="image" class="text-center"/>
		<ul id = "result" class="nav nav-tabs">
			<li role="presentation" class="active" ><a href="{% url 'index' %}">首页</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'news' %}">农业新闻</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'shichangjiage' %}">市场价格</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'shiyongjishu' %}">实用技术</a></li>
			<li role="presentation"><a href="{% url 'classfiy' 'zhengcefagui' %}">政策法规</a></li>
			{% if request.user.is_authenticated %}
				<li role="presentation"><a href="{% url 'user' 'history' %}">历史浏览</a></li>
				<li role="presentation"><a href="/myRecommend">我的推荐</a></li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'logout' %}"> 登出 </a> </li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'user' "info" %}"> {{ request.user.username  }} </a> </li>

			{% else %}
				<li class = "pull-right " role="presentation"> <a href="{% url 'login' %}"> 登录 </a> </li>
				<li class = "pull-right " role="presentation"> <a href="{% url 'register' %}"> 注册 </a> </li>
			{% endif %}
		</ul>
	</div>
    <div class="bdsharebuttonbox" style="right: 20px;"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></div>
    <div style="width: 800px;margin: 10px auto;">
        <h1 style="text-align: center">{{ news.title }}</h1>
        <span style="float: right">{{ news.updated_at }}</span>
        <br/>
        <hr />
        <p style="line-height: 30px;">{{ news.text }}</p>
    </div>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdPic":"","bdStyle":"0","bdSize":"16"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>
<div class="dialog" id="jsDialog">
    <!--提示弹出框-->
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <div  class="noactivebox dialogbox" id="jsUnactiveForm" >
        <h1>邮件验证提示</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="center">
            <img src="{% static 'images/send.png' %}"/>
            <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
            <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
            <p class="zy_success upmove"></p>
            <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
            <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
        </div>
    </div>
</div>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'img/1.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'img/2.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'img/3.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <h2>用户注册</h2>
                </div>
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'register' %}" autocomplete="off">
                        <input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />
                        <div class="form-group marb8 {% if register_form.errors.email %} errorput {% endif %}">
                            <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                            <input  type="text" id="id_email" name="email"  value="{{ register_form.email.empty_values }}" placeholder="账号/邮箱/手机号"/>
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.password %} errorput {% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="" placeholder="请输入6-20位非中文字符密码" />
                        </div>
						<div class="form-group marb8 {% if register_form.errors.password %} errorput {% endif %}">
                            <label>确&nbsp;认&nbsp;密&nbsp;码</label>
                            <input type="password" id="id_password2" name="password"  value="" placeholder="再次输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1{% if register_form.errors.captcha %} errorput {% endif %} ">
                            <label>验&nbsp;证&nbsp;码</label>
                            {{ register_form.captcha }}
                        </div>
                        <div class="error btns" id="jsEmailTips">{{ msg }}{% for error in  register_form.errors.values %}{{ error }}{% endfor %}</div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册" />
                    <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />
                    {% csrf_token %}
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="{% url 'login' %}">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>